language: node_js
node_js:
- 4.2
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- redis-server
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=test
before_script:
- npm install -g npm@3
- npm install
- npm run build
branches:
  only:
  - master
script:
- npm test
notifications:
  email: false