language: node_js
node_js:
- 4.2
services:
- redis-server
env:
  global:
  - NODE_ENV=test
before_script:
- npm install
- npm run build
branches:
  only:
  - master
script:
- npm test
notifications:
  email: false